const fs = require('node:fs');
const path = require('node:path');
const jsFile = path.join(__dirname, '..', 'public', 'js', 'core', 'federation-polish.js');
fs.mkdirSync(path.dirname(jsFile), { recursive: true });
const js = String.raw`
(function(){
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const module=document.body.dataset.frmModule||'';const logo='/api/brand/icon?v=2026-07-14-frm-polish-v2';
async function api(url,opt){const r=await fetch(url,{credentials:'include',cache:'no-store',...(opt||{})});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.message||String(r.status));return d;}
function arr(d,keys){for(const k of keys){if(Array.isArray(d&&d[k]))return d[k];}return Array.isArray(d)?d:[]}
function esc(v){return String(v??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function nameOf(u){return u?.profile?.username||u?.profile?.displayName||u?.name||u?.username||u?.discordId||'Atleta'}
function teamName(t){return t?.name||t?.teamName||t?.tag||'Clube'}
function img(v){return v||logo}
function empty(t){return `<div class="frm-empty">${esc(t)}</div>`}
function fmt(v){if(!v)return 'data em definição';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}
async function setupTop(){try{const me=await api('/api/me');const u=me.user||{};$$('[data-frm-login]').forEach(a=>{a.innerHTML=`<img class="frm-profile-avatar" src="${esc(img(u.avatar))}" alt="Perfil"/>`;a.classList.remove('frm-btn');a.title='Abrir perfil';});}catch{}try{const n=await api('/api/notifications');$$('[data-frm-unread],[data-frm-mail]').forEach(b=>b.textContent=String(n.unread||0));}catch{}}
async function overview(){try{return await api('/api/federation/overview')}catch{const [t,p,e]=await Promise.allSettled([api('/api/teams'),api('/api/players'),api('/api/events')]);return{teams:t.value?.teams||[],players:p.value?.players||p.value?.users||[],events:e.value?.events||[],stats:{}}}}
async function dashboard(){const d=await overview();const s=d.stats||{};const vals={clubes:s.clubes??d.teams?.length??0,atletas:s.atletas??d.players?.length??0,competicoes:s.competicoes??d.events?.length??0,partidas:s.partidas??0,gols:s.gols??0};Object.entries(vals).forEach(([k,v])=>$$(`[data-stat="${k}"]`).forEach(e=>e.textContent=String(v)));if($('#seasonDates')){$('#seasonDates').textContent=`Início ${fmt(d.season?.startAt)} • Término ${fmt(d.season?.endAt)}`;}const rank=$('#homeClubRanking');if(rank){const teams=(d.teams||[]).slice(0,5);rank.innerHTML=teams.length?teams.map((t,i)=>`<div class="frm-list-row"><b class="frm-rank-badge">${i+1}</b><div><strong>${esc(teamName(t))}</strong><br><small>${esc(t.tag||'Sem pontuação registrada')}</small></div><span>0 pts</span></div>`).join(''):empty('Nenhum clube cadastrado ainda.')}}
async function competitions(){const d=await overview();const ev=d.events||[];const nexus=ev.find(e=>/nexus/i.test(e.name||e.title||''));const main=nexus||{name:'Nexus Cup 1ª Edição',matchFormat:'MD3',teamLimit:32,startAt:'2026-07-18T19:30:00-03:00'};const list=$('#competitionsList');if(!list)return;const all=[main,{name:'Liga Hollow Nexus',soon:true},{name:'Copa Hollow Nexus',soon:true},{name:'Supercopa HNX',soon:true},{name:'Torneio de Novatos',soon:true}];list.innerHTML=all.map(e=>`<article class="frm-card"><span class="frm-pill ${e.soon?'':'green'}">${e.soon?'Em breve':'Ativa'}</span><h2>${esc(e.name||e.title)}</h2><p>${e.soon?'Competição planejada. Ainda sem inscrições abertas.':`Formato ${esc(e.matchFormat||'MD3')} • Limite ${esc(e.teamLimit||32)} clubes • Início ${fmt(e.startAt)}`}</p><a class="frm-btn ${e.soon?'':'primary'}" href="${e.soon?'/pages/calendario.html':'/pages/eventos.html'}">${e.soon?'Ver calendário':'Detalhes / inscrição'}</a></article>`).join('')}
async function cafe(){const data=await api('/api/federation/cafe-com-leite').catch(()=>({queue:[],ranking:[]}));const q=$('#cafeQueue'),r=$('#cafeRanking');if(q)q.innerHTML=data.queue?.length?data.queue.map(x=>`<div class="frm-list-row"><img class="frm-avatar" src="${esc(img(x.avatar))}"><div><strong>${esc(x.name)}</strong><br><small>${esc(x.role||'Livre')} • ${esc(x.note||'Sem observação')}</small></div><span class="frm-pill">Fila</span></div>`).join(''):empty('Fila vazia. Entre na fila para iniciar o Café com Leite.');if(r)r.innerHTML=data.ranking?.length?data.ranking.map((x,i)=>`<div class="frm-list-row"><b>${i+1}</b><div><strong>${esc(x.name)}</strong><br><small>${x.matches||0} participações</small></div><span>${x.points||0} pts</span></div>`).join(''):empty('Ranking individual começa zerado.');const f=$('#cafeQueueForm');if(f&&!f.dataset.ready){f.dataset.ready=1;f.addEventListener('submit',async ev=>{ev.preventDefault();const fd=new FormData(f);await api('/api/federation/cafe-com-leite/queue',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role:fd.get('role'),note:fd.get('note')})});f.reset();cafe();})}}
async function calendar(){const grid=$('#calendarGrid');if(!grid)return;const d=await overview();const names=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];let html=names.map(x=>`<div class="frm-calendar-head">${x}</div>`).join('');const evs=[{day:18,label:'Nexus Cup 1ª Edição',href:'/pages/competicoes.html'},{day:20,label:'Café com Leite',href:'/pages/eventos.html'}];(d.events||[]).forEach(e=>{const dt=new Date(e.startAt||e.date||'');if(!isNaN(dt)&&dt.getMonth()===6&&dt.getFullYear()===2026)evs.push({day:dt.getDate(),label:e.name||e.title||'Competição',href:'/pages/competicoes.html'})});for(let i=0;i<3;i++)html+='<div class="frm-day out"></div>';for(let day=1;day<=31;day++){html+=`<div class="frm-day"><strong>${day}</strong>${evs.filter(e=>e.day===day).map(e=>`<a class="frm-event-dot" href="${e.href}">${esc(e.label)}</a>`).join('')}</div>`}grid.innerHTML=html}
async function clubs(){const [td,pd]=await Promise.allSettled([api('/api/teams'),api('/api/players')]);const teams=td.value?.teams||[],players=arr(pd.value||{},['players','users','items']);const box=$('#clubsList');if(!box)return;box.innerHTML=teams.length?teams.map(t=>`<article class="frm-card" data-team-id="${esc(t.id)}"><div class="frm-list-row"><img class="frm-team-logo" src="${esc(img(t.logo||t.logoUrl))}"><div><h3>${esc(teamName(t))}</h3><p>${esc(t.tag||'Clube afiliado')}</p></div><span class="frm-pill">${(t.playerDetails||t.players||[]).length}/5</span></div><p>Capitão: ${esc(t.captainName||t.ownerName||'não definido')}</p><div class="frm-toolbar"><a class="frm-btn" href="/pages/elencos.html">Ver elenco</a>${t.canManage?`<button class="frm-btn primary" data-invite="${esc(t.id)}">Convidar jogador</button>`:''}</div></article>`).join(''):empty('Nenhum clube cadastrado ainda.');$$('[data-invite]').forEach(btn=>btn.onclick=()=>inviteModal(btn.dataset.invite,teams,players))}
function inviteModal(teamId,teams,players){const team=teams.find(t=>String(t.id)===String(teamId));const panel=$('#frmModalPanel');panel.innerHTML=`<h2>Convidar jogador para ${esc(teamName(team))}</h2><p class="frm-muted">O jogador receberá convite no Correio do site.</p><select class="frm-select" id="invitePlayer">${players.map(p=>`<option value="${esc(p.id||p.discordId)}">${esc(nameOf(p))}</option>`).join('')}</select><select class="frm-select" id="inviteSlot" style="margin-top:10px"><option value="player">Titular</option><option value="reserve">Reserva</option></select><textarea class="frm-textarea" id="inviteNote" placeholder="Mensagem opcional" style="margin-top:10px"></textarea><div class="frm-toolbar" style="margin-top:12px"><button class="frm-btn primary" id="sendInvite">Enviar convite</button><button class="frm-btn" id="closeInvite">Cancelar</button></div>`;$('#frmModal').classList.add('open');$('#closeInvite').onclick=()=>$('#frmModal').classList.remove('open');$('#sendInvite').onclick=async()=>{await api('/api/federation/team-invites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({teamId,playerId:$('#invitePlayer').value,rosterSlot:$('#inviteSlot').value,note:$('#inviteNote').value})});$('#frmModal').classList.remove('open');alert('Convite enviado para o Correio do jogador.')}}
async function rosters(){const d=await api('/api/teams').catch(()=>({teams:[]}));const box=$('#rostersList');if(!box)return;box.innerHTML=d.teams?.length?d.teams.map(t=>`<article class="frm-card"><h2>${esc(teamName(t))}</h2><div class="frm-list">${[...(t.playerDetails||[]),...(t.reserveDetails||[])].map(p=>`<div class="frm-list-row"><img class="frm-avatar" src="${esc(img(p.avatar))}"><div><strong>${esc(p.name)}</strong><br><small>${esc(p.type==='reserve'?'Reserva':'Titular')}</small></div><span class="frm-pill">${esc(p.profile?.primaryPosition||'Jogador')}</span></div>`).join('')||empty('Elenco ainda não preenchido.')}</div></article>`).join(''):empty('Nenhum elenco cadastrado.')}
async function players(){const [pd,td]=await Promise.allSettled([api('/api/players'),api('/api/teams')]);const players=arr(pd.value||{},['players','users','items']);const teams=td.value?.teams||[];const box=$('#playersList')||$('#marketPlayers');if(!box)return;box.innerHTML=players.length?players.map(p=>{const club=teams.find(t=>JSON.stringify(t).includes(p.discordId||p.id));return `<article class="frm-card"><div class="frm-list-row"><img class="frm-avatar" src="${esc(img(p.avatar))}"><div><h3>${esc(nameOf(p))}</h3><p>${esc(club?teamName(club):'Livre no mercado')}</p></div><span class="frm-pill">${esc(p.profile?.primaryPosition||'Atleta')}</span></div></article>`}).join(''):empty('Nenhum atleta registrado ainda.')}
async function rankings(){const [td,pd]=await Promise.allSettled([api('/api/teams'),api('/api/players')]);const teams=td.value?.teams||[],players=arr(pd.value||{},['players','users','items']);const cr=$('#clubRanking'),pr=$('#playerRanking');if(cr)cr.innerHTML=teams.length?teams.map((t,i)=>`<tr><td>${i+1}</td><td>${esc(teamName(t))}</td><td>0</td><td>0</td></tr>`).join(''):'<tr><td colspan="4">Nenhum clube cadastrado.</td></tr>';if(pr)pr.innerHTML=players.length?players.map((p,i)=>`<tr><td>${i+1}</td><td>${esc(nameOf(p))}</td><td>Livre</td><td>0</td></tr>`).join(''):'<tr><td colspan="4">Nenhum jogador cadastrado.</td></tr>'}
async function notifications(){const d=await api('/api/notifications').catch(()=>({notifications:[]}));const box=$('#notificationsList');if(!box)return;box.innerHTML=d.notifications?.length?d.notifications.map(n=>`<div class="frm-list-row"><div>✉</div><div><strong>${esc(n.title||'Mensagem')}</strong><br><small>${esc(n.message||n.note||'')}</small><br><small>${fmt(n.createdAt)}</small></div><div class="frm-toolbar">${n.type==='recruitment_invite'&&n.status==='pending'?`<button class="frm-btn primary" data-act="accept" data-id="${esc(n.id)}">Aceitar</button><button class="frm-btn danger" data-act="decline" data-id="${esc(n.id)}">Recusar</button>`:`<span class="frm-pill">${esc(n.status||'info')}</span>`}</div></div>`).join(''):empty('Nenhuma mensagem no Correio.');$$('[data-act]').forEach(b=>b.onclick=async()=>{await api('/api/notifications/'+b.dataset.id+'/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:b.dataset.act})});notifications();setupTop()})}
async function support(){const f=$('#supportForm');if(f&&!f.dataset.ready){f.dataset.ready=1;f.onsubmit=async ev=>{ev.preventDefault();const fd=new FormData(f);const st=$('#supportStatus');try{const d=await api('/api/support/tickets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({area:fd.get('area'),page:fd.get('page'),message:fd.get('message'),summary:fd.get('message')})});st.textContent='Ticket enviado: '+(d.ticket?.protocol||d.protocol||'registrado');f.reset()}catch(e){st.textContent='Erro: '+e.message}}}}
function tactics(){const board=$('#tacticBoard');if(!board)return;const defaults=[['A-GOL','GOL',8,50],['A-DEF','DEF',24,50],['A-ALA','ALA',39,30],['A-MEI','MEI',39,70],['A-ATA','ATA',49,50],['B-GOL','GOL',92,50],['B-DEF','DEF',76,50],['B-ALA','ALA',61,30],['B-MEI','MEI',61,70],['B-ATA','ATA',51,50]];const saved=JSON.parse(localStorage.getItem('frm:tactic')||'{}');defaults.forEach(([id,pos,x,y])=>{const s=saved[id]||{};const el=document.createElement('div');el.className='frm-player-token';el.dataset.token=id;el.style.left=(s.x||x)+'%';el.style.top=(s.y||y)+'%';el.innerHTML=`<span contenteditable="true">${esc(s.name||pos)}</span><b>${esc(pos)}</b>`;board.appendChild(el)});if(saved.ball){const b=$('[data-token="ball"]');b.style.left=saved.ball.x+'%';b.style.top=saved.ball.y+'%'}let drag=null;board.addEventListener('pointerdown',e=>{const t=e.target.closest('[data-token]');if(!t)return;drag=t;t.setPointerCapture?.(e.pointerId)});board.addEventListener('pointermove',e=>{if(!drag)return;const r=board.getBoundingClientRect();let x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;x=Math.max(3,Math.min(97,x));y=Math.max(5,Math.min(95,y));drag.style.left=x+'%';drag.style.top=y+'%'});board.addEventListener('pointerup',()=>drag=null);$('#saveTactic')?.addEventListener('click',()=>{const out={};$$('[data-token]',board).forEach(t=>{const key=t.dataset.token;out[key]={x:parseFloat(t.style.left),y:parseFloat(t.style.top),name:t.querySelector('span')?.textContent||''}});localStorage.setItem('frm:tactic',JSON.stringify(out));alert('Prancheta salva neste navegador.')});$('#resetTactic')?.addEventListener('click',()=>{localStorage.removeItem('frm:tactic');location.reload()})}
setupTop();({dashboard,competitions,events:cafe,calendar,clubs,rosters,players,market:players,rankings,notifications,support,tactics}[module]||function(){})();
})();
`;
const before = fs.existsSync(jsFile) ? fs.readFileSync(jsFile, 'utf8') : '';
if (before !== js) {
  fs.writeFileSync(jsFile, js, 'utf8');
  console.log('[Federacao] JS polish aplicado.');
} else {
  console.log('[Federacao] JS polish ja estava aplicado.');
}
