const fs = require('node:fs');
const path = require('node:path');
const ROOT = path.join(__dirname, '..');
const pagesDir = path.join(ROOT, 'public', 'pages');
const BUILD = '2026-07-14-frm-polish-v2';
const LOGO = '/api/brand/icon?v=' + BUILD;
const CSS = '/css/federation-polish.css?v=' + BUILD;
const JS = '/js/core/federation-polish.js?v=' + BUILD;
let changed = false;
function ensure(file){fs.mkdirSync(path.dirname(file),{recursive:true});}
function write(file,html){ensure(file);const before=fs.existsSync(file)?fs.readFileSync(file,'utf8'):'';if(before!==html){fs.writeFileSync(file,html,'utf8');changed=true;}}
function nav(active=''){
 const s=[['Federação',[['⌂','Início','/pages/dashboard.html'],['ⓘ','Sobre a Federação','/pages/federacao.html'],['▤','Regulamento','/pages/regulamento.html'],['▧','Atualizações','/pages/atualizacoes.html'],['?','Suporte','/pages/suporte.html']]],['Competitivo',[['♕','Competições','/pages/competicoes.html'],['▣','Eventos','/pages/eventos.html'],['⌘','Chaveamento','/pages/chaveamento.html'],['☷','Grupos','/pages/grupos.html'],['⊙','Resultados','/pages/resultados.html'],['⌁','Rankings','/pages/rankings.html'],['▦','Calendário','/pages/calendario.html']]],['Clubes',[['♙','Clubes Afiliados','/pages/clubes.html'],['✥','Solicitar Afiliação','/pages/formularios.html'],['♧','Elencos','/pages/elencos.html'],['▣','Prancheta Tática','/pages/prancheta-tatica.html']]],['Atletas',[['♟','Jogadores Registrados','/pages/atletas.html'],['✧','Mercado / Recrutamento','/pages/mercado.html'],['⊙','Ranking de Jogadores','/pages/rankings.html'],['↔','Transferências','/pages/transferencias.html']]],['Administração',[['▤','Formulários','/pages/formularios.html'],['ⓘ','Permissões','/pages/permissoes.html'],['⚙','Configurações','/pages/configuracoes.html'],['◉','Análise de Partidas','/pages/analise-partidas.html']]]];
 return s.map(([t,l])=>`<div class="frm-nav-title">${t}</div>`+l.map(([i,n,h])=>`<a${h===active?' class="active"':''} href="${h}"><i>${i}</i><b>${n}</b></a>`).join('')).join('');}
function footer(){return `<footer class="frm-footer"><div><div class="frm-footer-brand"><img src="${LOGO}"/><div><strong>the HOLLOW NEXUS <span class="frm-accent">FRM</span></strong><p>Federação Comunitária de Rematch</p></div></div><p>Elevando o cenário competitivo de Rematch.</p></div><div><h4>Links rápidos</h4><p><a href="/pages/regulamento.html">Regulamento</a></p><p><a href="/pages/termos.html">Termos de Uso</a></p><p><a href="/pages/privacidade.html">Privacidade</a></p></div><div><h4>Contato</h4><p>Contato oficial em definição</p><p><a href="/pages/suporte.html">Suporte</a></p><p><a href="/api/discord/server/open" target="_blank">Discord Oficial</a></p></div><div><h4>Redes sociais</h4><div class="frm-socials"><span>𝕏</span><span>◎</span><span>▶</span><span>♪</span></div></div><div><h4>Legal</h4><p>Projeto comunitário independente. Não afiliado, patrocinado ou endossado pela Sloclap, Kepler Interactive ou Rematch.</p><p>© 2026 The Hollow Nexus FRM.</p></div></footer>`}
function shell(o){const tabs=[['inicio','Início','/pages/dashboard.html'],['federacao','Federação','/pages/federacao.html'],['competitivo','Competitivo','/pages/competicoes.html'],['clubes','Clubes','/pages/clubes.html'],['atletas','Atletas','/pages/atletas.html'],['admin','Administração','/pages/administracao.html']];return `<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>${o.title} | Hollow Nexus FRM</title><link rel="icon" href="${LOGO}"/><link rel="stylesheet" href="${CSS}"/></head><body class="frm-polish-page" data-frm-module="${o.module||''}"><div class="frm-shell"><aside class="frm-sidebar"><div class="frm-brand"><img src="${LOGO}"/><div><small>the</small><strong>HOLLOW NEXUS <span>FRM</span></strong><p>Federação Comunitária</p></div></div><nav class="frm-nav">${nav(o.href)}</nav></aside><main class="frm-main"><header class="frm-header"><nav class="frm-tabs">${tabs.map(([k,l,u])=>`<a class="${k===o.tab?'active':''}" href="${u}">${l}</a>`).join('')}</nav><div class="frm-header-actions"><a class="frm-btn" data-frm-login href="/pages/perfil.html">♙ Entrar / Painel</a><a class="frm-btn discord" href="/api/discord/server/open" target="_blank">💬 Discord</a><a class="frm-icon" href="/pages/notificacoes.html">🔔<b class="frm-badge" data-frm-unread>0</b></a><a class="frm-icon" href="/pages/correio.html">✉<b class="frm-badge" data-frm-mail>0</b></a></div></header>${o.hero||''}${o.body||''}${footer()}</main></div><div class="frm-modal" id="frmModal"><div class="frm-modal-panel" id="frmModalPanel"></div></div><script src="${JS}"></script></body></html>`}
function hero(title,text){return `<section class="frm-page-hero"><div><p class="frm-tag">Hollow Nexus FRM</p><h1><span class="frm-the">the</span>${title}</h1><p>${text}</p></div><img src="${LOGO}"/></section>`}
const pages={
 'dashboard.html':shell({title:'Início',tab:'inicio',href:'/pages/dashboard.html',module:'dashboard',hero:`<section class="frm-page-hero"><div><p class="frm-tag">Bem-vindo à</p><h1><span class="frm-the">the</span>HOLLOW NEXUS <span>FRM</span></h1><p>Federação Comunitária de Rematch. Estrutura oficial para clubes, atletas, competições, calendário, suporte e rankings.</p><p id="seasonDates">Carregando temporada real...</p><div class="frm-toolbar" style="margin-top:18px"><a class="frm-btn primary" href="/pages/clubes.html">Afiliar Clube</a><a class="frm-btn" href="/pages/competicoes.html">Ver Competições</a><a class="frm-btn" href="/pages/rankings.html">Ranking Oficial</a><a class="frm-btn" href="/pages/regulamento.html">Regulamento</a></div></div><img src="${LOGO}"/></section>`,body:`<section class="frm-grid four"><article class="frm-card"><span>Clubes afiliados</span><b class="frm-metric" data-stat="clubes">0</b></article><article class="frm-card"><span>Atletas registrados</span><b class="frm-metric" data-stat="atletas">0</b></article><article class="frm-card"><span>Competições ativas</span><b class="frm-metric" data-stat="competicoes">0</b></article><article class="frm-card"><span>Partidas disputadas</span><b class="frm-metric" data-stat="partidas">0</b></article></section><section class="frm-grid" style="margin-top:12px"><article class="frm-card"><h2>Competições em destaque</h2><div class="frm-list"><div class="frm-list-row"><img class="frm-team-logo" src="${LOGO}"><div><strong>Nexus Cup 1ª Edição</strong><br><small>Ativa / MD3 / 32 vagas</small></div><a class="frm-btn" href="/pages/competicoes.html">Abrir</a></div><div class="frm-list-row"><span>◌</span><div><strong>Liga Hollow Nexus</strong><br><small>Em breve</small></div><span class="frm-pill">Em breve</span></div><div class="frm-list-row"><span>◌</span><div><strong>Copa Hollow Nexus</strong><br><small>Em breve</small></div><span class="frm-pill">Em breve</span></div></div></article><article class="frm-card"><h2>Ranking de clubes</h2><div id="homeClubRanking" class="frm-list"></div></article><article class="frm-card"><h2>Últimas notícias</h2><div class="frm-list"><div class="frm-list-row"><span>🟣</span><div><strong>Portal FRM atualizado</strong><br><small>Áreas novas sem visual antigo.</small></div><a class="frm-btn" href="/pages/atualizacoes.html">Ver</a></div><div class="frm-list-row"><span>☕</span><div><strong>Café com Leite</strong><br><small>Evento comunitário separado das competições.</small></div><a class="frm-btn" href="/pages/eventos.html">Abrir</a></div></div></article></section>`}),
 'competicoes.html':shell({title:'Competições',tab:'competitivo',href:'/pages/competicoes.html',module:'competitions',hero:hero('Competições','Nexus Cup e competições oficiais ficam aqui. Eventos sociais ficam separados.'),body:`<section class="frm-grid" id="competitionsList"></section>`}),
 'eventos.html':shell({title:'Eventos',tab:'competitivo',href:'/pages/eventos.html',module:'events',hero:hero('Eventos','Eventos comunitários, Café com Leite, filas e ranking individual.'),body:`<section class="frm-grid two"><article class="frm-card"><h2>Café com Leite</h2><p>Evento aberto do servidor para filas, amistosos e ranking individual.</p><form id="cafeQueueForm" class="frm-list"><input class="frm-input" name="role" placeholder="Posição / função no Rematch"/><textarea class="frm-textarea" name="note" placeholder="Observação opcional"></textarea><button class="frm-btn primary" type="submit">Entrar na fila</button></form></article><article class="frm-card"><h2>Ranking individual</h2><div id="cafeRanking" class="frm-list"></div></article></section><section class="frm-card" style="margin-top:12px"><h2>Fila atual</h2><div id="cafeQueue" class="frm-list"></div></section>`}),
 'calendario.html':shell({title:'Calendário',tab:'competitivo',href:'/pages/calendario.html',module:'calendar',hero:hero('Calendário de Julho','Calendário mensal da federação com Nexus Cup e eventos comunitários.'),body:`<section class="frm-card"><div class="frm-toolbar"><span class="frm-pill">Julho 2026</span><a class="frm-btn" href="/pages/competicoes.html">Competições</a><a class="frm-btn" href="/pages/eventos.html">Eventos</a></div><div id="calendarGrid" class="frm-calendar"></div></section>`}),
 'clubes.html':shell({title:'Clubes Afiliados',tab:'clubes',href:'/pages/clubes.html',module:'clubs',hero:hero('Clubes Afiliados','Clubes cadastrados, elencos, capitães e ações de recrutamento.'),body:`<section class="frm-toolbar"><input class="frm-input" id="clubSearch" placeholder="Buscar clube" style="max-width:340px"/><a class="frm-btn primary" href="/pages/formularios.html">Solicitar afiliação</a></section><section class="frm-grid" id="clubsList"></section>`}),
 'times.html':shell({title:'Clubes Afiliados',tab:'clubes',href:'/pages/clubes.html',module:'clubs',hero:hero('Clubes Afiliados','Clubes cadastrados, elencos, capitães e ações de recrutamento.'),body:`<section class="frm-toolbar"><input class="frm-input" id="clubSearch" placeholder="Buscar clube" style="max-width:340px"/><a class="frm-btn primary" href="/pages/formularios.html">Solicitar afiliação</a></section><section class="frm-grid" id="clubsList"></section>`}),
 'elencos.html':shell({title:'Elencos',tab:'clubes',href:'/pages/elencos.html',module:'rosters',hero:hero('Elencos','Jogadores vinculados aos clubes. Convites aceitos pelo Correio entram aqui.'),body:`<section class="frm-grid" id="rostersList"></section>`}),
 'atletas.html':shell({title:'Atletas Registrados',tab:'atletas',href:'/pages/atletas.html',module:'players',hero:hero('Atletas Registrados','Jogadores registrados na federação.'),body:`<section class="frm-toolbar"><input class="frm-input" id="playerSearch" placeholder="Buscar atleta" style="max-width:340px"/><a class="frm-btn" href="/pages/mercado.html">Mercado</a></section><section class="frm-grid" id="playersList"></section>`}),
 'jogadores.html':shell({title:'Atletas Registrados',tab:'atletas',href:'/pages/atletas.html',module:'players',hero:hero('Atletas Registrados','Jogadores registrados na federação.'),body:`<section class="frm-toolbar"><input class="frm-input" id="playerSearch" placeholder="Buscar atleta" style="max-width:340px"/><a class="frm-btn" href="/pages/mercado.html">Mercado</a></section><section class="frm-grid" id="playersList"></section>`}),
 'mercado.html':shell({title:'Mercado / Recrutamento',tab:'atletas',href:'/pages/mercado.html',module:'market',hero:hero('Mercado / Recrutamento','Capitães encontram atletas livres e enviam convite pelo Correio.'),body:`<section class="frm-grid two"><article class="frm-card"><h2>Atletas disponíveis</h2><div id="marketPlayers" class="frm-list"></div></article><article class="frm-card"><h2>Como funciona</h2><p>O capitão envia um convite. O jogador recebe no Correio com botões de aceitar ou recusar. Só após aceitar ele entra no elenco.</p></article></section>`}),
 'recrutamento.html':shell({title:'Mercado / Recrutamento',tab:'atletas',href:'/pages/mercado.html',module:'market',hero:hero('Mercado / Recrutamento','Capitães encontram atletas livres e enviam convite pelo Correio.'),body:`<section class="frm-grid two"><article class="frm-card"><h2>Atletas disponíveis</h2><div id="marketPlayers" class="frm-list"></div></article><article class="frm-card"><h2>Como funciona</h2><p>O jogador só entra no elenco depois de aceitar o convite no Correio.</p></article></section>`}),
 'rankings.html':shell({title:'Rankings',tab:'competitivo',href:'/pages/rankings.html',module:'rankings',hero:hero('Rankings','Ranking real de clubes e atletas. Sem resultado registrado, a pontuação fica zerada.'),body:`<section class="frm-grid two"><article class="frm-card"><h2>Ranking de Clubes</h2><table class="frm-table"><thead><tr><th>#</th><th>Clube</th><th>Pts</th><th>J</th></tr></thead><tbody id="clubRanking"></tbody></table></article><article class="frm-card"><h2>Ranking de Jogadores</h2><table class="frm-table"><thead><tr><th>#</th><th>Atleta</th><th>Clube</th><th>Pts</th></tr></thead><tbody id="playerRanking"></tbody></table></article></section>`}),
 'notificacoes.html':shell({title:'Notificações',tab:'inicio',href:'/pages/notificacoes.html',module:'notifications',hero:hero('Notificações','Avisos do site, convites de recrutamento e respostas importantes.'),body:`<section class="frm-card"><div id="notificationsList" class="frm-list"></div></section>`}),
 'correio.html':shell({title:'Correio',tab:'inicio',href:'/pages/correio.html',module:'notifications',hero:hero('Correio','Convites de time aparecem aqui com aceitar ou recusar.'),body:`<section class="frm-card"><div id="notificationsList" class="frm-list"></div></section>`}),
 'suporte.html':shell({title:'Suporte',tab:'federacao',href:'/pages/suporte.html',module:'support',hero:hero('Suporte','Abra um ticket para staff. O pedido fica salvo no site e no histórico da equipe.'),body:`<section class="frm-grid two"><article class="frm-card"><h2>Abrir ticket</h2><form id="supportForm" class="frm-list"><input class="frm-input" name="area" placeholder="Área: inscrição, time, bug, outro" required/><input class="frm-input" name="page" placeholder="Página ou setor afetado"/><textarea class="frm-textarea" name="message" placeholder="Descreva o problema" required></textarea><button class="frm-btn primary" type="submit">Enviar ticket</button></form></article><article class="frm-card"><h2>Status</h2><div id="supportStatus" class="frm-empty">Aguardando envio.</div></article></section>`}),
 'atualizacoes.html':shell({title:'Atualizações',tab:'federacao',href:'/pages/atualizacoes.html',module:'updates',hero:hero('Atualizações','Histórico oficial de mudanças do site e bot.'),body:`<section class="frm-grid"><article class="frm-card"><span class="frm-pill green">14/07/2026 • 12:58 BRT</span><h2>Polimento FRM e funções reais</h2><p>Calendário separado, Café com Leite, competições Nexus Cup, rankings reais e páginas sem estrutura antiga.</p></article><article class="frm-card"><span class="frm-pill">14/07/2026</span><h2>Migração completa FRM</h2><p>Áreas novas ganharam shell visual próprio e páginas funcionais.</p></article></section>`}),
 'prancheta-tatica.html':shell({title:'Prancheta Tática',tab:'clubes',href:'/pages/prancheta-tatica.html',module:'tactics',hero:hero('Prancheta Tática 5v5','Campo Rematch com 5 jogadores por lado, bola móvel, gols e tokens arrastáveis.'),body:`<section class="frm-board-wrap"><div class="frm-board" id="tacticBoard"><div class="frm-goal left"></div><div class="frm-goal right"></div><div class="frm-ball" data-token="ball" style="left:50%;top:50%">⚽</div></div><aside class="frm-card"><h2>Formação</h2><p>Arraste os círculos no campo. Clique no nome para editar jogador/posição.</p><button class="frm-btn primary" id="saveTactic">Salvar prancheta</button><button class="frm-btn" id="resetTactic">Resetar</button><div class="frm-empty" style="margin-top:12px">Limite visual: 5 jogadores por equipe, incluindo goleiro.</div></aside></section>`})
};
for(const [name,html] of Object.entries(pages)) write(path.join(pagesDir,name),html);
console.log(changed?'[Federacao] Paginas polish aplicadas.':'[Federacao] Paginas polish ja estavam aplicadas.');
