const fs = require('node:fs');
const path = require('node:path');
const jsFile = path.join(__dirname, '..', 'public', 'js', 'core', 'federation-polish.js');

if (fs.existsSync(jsFile)) {
  let js = fs.readFileSync(jsFile, 'utf8');
  if (!js.includes('FRM_FINAL_FIXES_V1')) {
    js += String.raw`

/* FRM_FINAL_FIXES_V1 */
(function(){
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const module=document.body.dataset.frmModule||'';
async function api(url,opt){const r=await fetch(url,{credentials:'include',cache:'no-store',...(opt||{})});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.message||String(r.status));return d;}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function nameOf(u){return u?.profile?.username||u?.profile?.displayName||u?.name||u?.username||u?.discordId||'Atleta'}
function teamName(t){return t?.name||t?.teamName||t?.tag||'Clube'}
function logo(v){return v||'/api/brand/icon?v=frm-final-fixes-v1'}
function arr(d,keys){for(const k of keys){if(Array.isArray(d&&d[k]))return d[k];}return Array.isArray(d)?d:[]}
async function data(){const [teams,players,overview,rank] = await Promise.allSettled([api('/api/teams'),api('/api/players'),api('/api/federation/overview'),api('/api/federation/ranking-settings')]);return{teams:teams.value?.teams||[],players:arr(players.value||{},['players','users','items']),overview:overview.value||{},settings:rank.value?.settings||{}}}
function setCalendarNexus(){const grid=$('#calendarGrid');if(!grid)return;const names=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];let html=names.map(x=>`<div class="frm-calendar-head">${x}</div>`).join('');for(let i=0;i<3;i++)html+='<div class="frm-day out"></div>';for(let day=1;day<=31;day++){const items=[];if(day===18)items.push('<a class="frm-event-dot" href="/pages/competicoes.html">Nexus Cup 1ª Edição • 19:30</a>');if(day===20)items.push('<a class="frm-event-dot" href="/pages/eventos.html">Café com Leite • Discord</a>');html+=`<div class="frm-day"><strong>${day}</strong>${items.join('')}</div>`;}grid.innerHTML=html;}
async function createClub(){const f=$('#clubCreateForm');if(!f||f.dataset.ready)return;f.dataset.ready=1;f.addEventListener('submit',async ev=>{ev.preventDefault();const fd=new FormData(f);const status=$('#clubCreateStatus');try{const payload=Object.fromEntries(fd.entries());const d=await api('/api/federation/clubs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});status.textContent='Clube criado com sucesso. Abrindo perfil...';setTimeout(()=>location.href='/pages/perfil-clube.html?id='+encodeURIComponent(d.team?.id||''),700);}catch(e){status.textContent='Erro: '+e.message;}})}
async function fixCompetitions(){const box=$('#competitionsList');if(!box)return;let d={};try{d=await api('/api/federation/overview')}catch{}const evs=d.events||[];let nexus=evs.find(e=>/nexus|cup/i.test(String(e.name||e.title||'')))||d.nexusCup; if(!nexus)nexus={name:'Nexus Cup 1ª Edição',matchFormat:'MD3',teamLimit:32,startAt:'2026-07-18T19:30:00-03:00',status:'open'};box.innerHTML=[nexus,{name:'Liga Hollow Nexus',soon:true},{name:'Copa Hollow Nexus',soon:true},{name:'Supercopa HNX',soon:true}].map(e=>`<article class="frm-card"><span class="frm-pill ${e.soon?'':'green'}">${e.soon?'Em breve':'Ativa'}</span><h2>${esc(e.name||e.title)}</h2><p>${e.soon?'Competição planejada. Ainda indisponível.':`Formato ${esc(e.matchFormat||'MD3')} • Limite ${esc(e.teamLimit||32)} clubes • Início 18/07/2026 19:30`}</p><a class="frm-btn ${e.soon?'':'primary'}" href="${e.soon?'/pages/calendario.html':'/pages/eventos.html'}">${e.soon?'Calendário':'Detalhes'}</a></article>`).join('');}
async function fixEvents(){const f=$('#cafeQueueForm');if(f){f.outerHTML='<div class="frm-card"><h2>Como participar</h2><p>O Café com Leite acontece pelo Discord oficial. Entre no servidor, acompanhe o canal do evento e siga as instruções da equipe para entrar na fila, confirmar presença e registrar pontuação.</p><a class="frm-btn discord" href="/api/discord/server/open" target="_blank">Abrir Discord</a></div>';}const q=$('#cafeQueue');if(q)q.innerHTML='<div class="frm-empty">Fila controlada pelo Discord oficial.</div>';}
async function fixRankings(){const d=await data();const cr=$('#clubRanking'),pr=$('#playerRanking');if(cr)cr.innerHTML=d.teams.length?d.teams.map((t,i)=>{const s=d.settings['club:'+t.id]||{};return `<tr><td>${i+1}</td><td><a href="/pages/perfil-clube.html?id=${encodeURIComponent(t.id||'')}">${esc(teamName(t))}</a></td><td>${Number(s.points||0)}</td><td>${Number(s.wins||0)}</td></tr>`}).join(''):'<tr><td colspan="4">Nenhum clube cadastrado.</td></tr>';if(pr)pr.innerHTML=d.players.length?d.players.map((p,i)=>{const s=d.settings['player:'+p.id]||{};return `<tr><td>${i+1}</td><td><a href="/pages/perfil-jogador.html?id=${encodeURIComponent(p.id||p.discordId||'')}">${esc(nameOf(p))}</a></td><td>${esc(p.profile?.primaryPosition||'Atleta')}</td><td>${Number(s.points||0)}</td></tr>`}).join(''):'<tr><td colspan="4">Nenhum jogador cadastrado.</td></tr>';const card=$('#rankingEditor');if(card)return;const host=document.querySelector('.frm-main');const section=document.createElement('section');section.className='frm-card';section.id='rankingEditor';section.innerHTML='<h2>Editar pontuação</h2><p class="frm-muted">Área administrativa para ajustar pontos enquanto o sistema de resultados ainda está sendo alimentado.</p><form class="frm-rank-editor" id="rankEditForm"><select class="frm-select" name="target"></select><input class="frm-input" name="points" type="number" placeholder="Pontos"/><input class="frm-input" name="wins" type="number" placeholder="Vitórias"/><button class="frm-btn primary" type="submit">Salvar</button></form><p id="rankEditStatus" class="frm-muted"></p>';host.insertBefore(section, document.querySelector('.frm-footer'));const sel=section.querySelector('select');sel.innerHTML=[...d.teams.map(t=>`<option value="club:${esc(t.id)}">Clube • ${esc(teamName(t))}</option>`),...d.players.map(p=>`<option value="player:${esc(p.id||p.discordId)}">Atleta • ${esc(nameOf(p))}</option>`)].join('');section.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const fd=new FormData(ev.target);const [targetType,targetId]=String(fd.get('target')).split(':');try{await api('/api/federation/ranking-settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetType,targetId,points:fd.get('points'),wins:fd.get('wins')})});$('#rankEditStatus').textContent='Pontuação salva.';setTimeout(()=>location.reload(),500);}catch(e){$('#rankEditStatus').textContent='Erro: '+e.message;}};}
async function profiles(){const qs=new URLSearchParams(location.search);const id=qs.get('id')||'';const d=await data();if(module==='player-profile'){const p=d.players.find(x=>String(x.id||'')===id||String(x.discordId||'')===id)||d.players[0];const box=$('#playerProfile');if(box)box.innerHTML=p?`<div class="frm-profile-cover"></div><div class="frm-player-profile"><img class="frm-avatar" style="width:96px;height:96px" src="${esc(logo(p.avatar))}"><div><h2>${esc(nameOf(p))}</h2><p>${esc(p.profile?.bio||'Atleta registrado na Hollow Nexus FRM.')}</p><span class="frm-pill">${esc(p.profile?.primaryPosition||'Atleta')}</span></div></div><section class="frm-grid two" style="margin-top:12px"><article class="frm-card"><h3>Conexões</h3><p>Discord: ${esc(p.discordId||'não vinculado')}</p><p>Steam/Xbox: ${esc(p.profile?.steamId||p.profile?.xboxGamertag||'não informado')}</p></article><article class="frm-card"><h3>Competitivo</h3><p>Pontos: ${(d.settings['player:'+p.id]?.points)||0}</p><p>Status: ${esc(p.teamName||'Livre')}</p></article></section>`:'<div class="frm-empty">Atleta não encontrado.</div>';}
if(module==='club-profile'){const t=d.teams.find(x=>String(x.id||'')===id)||d.teams[0];const box=$('#clubProfile');if(box)box.innerHTML=t?`<div class="frm-profile-cover"></div><div class="frm-team-profile"><img class="frm-team-logo" style="width:96px;height:96px" src="${esc(logo(t.logo||t.logoUrl))}"><div><h2>${esc(teamName(t))}</h2><p>${esc(t.description||'Clube afiliado à Hollow Nexus FRM.')}</p><span class="frm-pill">${esc(t.tag||'FRM')}</span></div></div><section class="frm-grid two" style="margin-top:12px"><article class="frm-card"><h3>Elenco</h3><div class="frm-list">${[...(t.playerDetails||[]),...(t.reserveDetails||[])].map(p=>`<div class="frm-list-row"><img class="frm-avatar" src="${esc(logo(p.avatar))}"><div><strong>${esc(p.name)}</strong><br><small>${esc(p.type||'jogador')}</small></div></div>`).join('')||'<div class="frm-empty">Elenco em formação.</div>'}</div></article><article class="frm-card"><h3>Dados</h3><p>Capitão: ${esc(t.captainName||t.ownerName||'não definido')}</p><p>Pontos: ${(d.settings['club:'+t.id]?.points)||0}</p></article></section>`:'<div class="frm-empty">Clube não encontrado.</div>';}}
async function transfers(){const f=$('#transferForm');if(!f)return;const d=await data();const p=$('#transferPlayer'),from=$('#transferFrom'),to=$('#transferTo');p.innerHTML=d.players.map(x=>`<option value="${esc(x.id||x.discordId)}">${esc(nameOf(x))}</option>`).join('');from.innerHTML=d.teams.map(x=>`<option value="${esc(x.id)}">${esc(teamName(x))}</option>`).join('');to.innerHTML=from.innerHTML;f.onsubmit=async ev=>{ev.preventDefault();const fd=new FormData(f);try{await api('/api/federation/transfers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(fd.entries()))});$('#transferStatus').textContent='Transferência solicitada.';}catch(e){$('#transferStatus').textContent='Erro: '+e.message;}};}
function tacticsPlus(){const board=$('#tacticBoard');if(!board)return;let tools=document.querySelector('.frm-board-tools');if(!tools){tools=document.createElement('div');tools.className='frm-board-tools';tools.innerHTML='<button class="frm-btn" data-add-player>Adicionar jogador</button><button class="frm-btn" data-add-opp>Adicionar adversário</button><button class="frm-btn" data-reset-board>Resetar</button><span class="frm-pill">Arraste jogadores e bola</span>';board.parentNode.insertBefore(tools,board);}function add(label,opp){const el=document.createElement('div');el.className='frm-player-token '+(opp?'opp':'');el.dataset.token='custom-'+Date.now()+Math.random();el.style.left=opp?'70%':'30%';el.style.top='50%';el.innerHTML=`<span contenteditable="true">${label}</span><b>${opp?'ADV':'HN'}</b>`;board.appendChild(el);}tools.querySelector('[data-add-player]').onclick=()=>add('Jogador',false);tools.querySelector('[data-add-opp]').onclick=()=>add('Adversário',true);tools.querySelector('[data-reset-board]').onclick=()=>{localStorage.removeItem('frm:tactic');location.reload();};}
function linksProfiles(){document.addEventListener('click',e=>{const a=e.target.closest('[data-player-profile]');if(a)location.href='/pages/perfil-jogador.html?id='+encodeURIComponent(a.dataset.playerProfile);const c=e.target.closest('[data-club-profile]');if(c)location.href='/pages/perfil-clube.html?id='+encodeURIComponent(c.dataset.clubProfile);});}
(async()=>{if(module==='calendar')setCalendarNexus();if(module==='affiliate')createClub();if(module==='competitions')fixCompetitions();if(module==='events')fixEvents();if(module==='rankings')fixRankings();if(module==='player-profile'||module==='club-profile')profiles();if(module==='transfers')transfers();if(module==='tactics')tacticsPlus();linksProfiles();})();
})();
`;
    fs.writeFileSync(jsFile, js, 'utf8');
    console.log('[Federacao] JS final fixes aplicado.');
  } else {
    console.log('[Federacao] JS final fixes ja estava aplicado.');
  }
}
